
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpmmlwxhthvtiolgjosd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwbW1sd3hodGh2dGlvbGdqb3NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMjM0NzMsImV4cCI6MjA1OTg5OTQ3M30.oXnSGlBHAQVve0cWu9H7uMa0uEI5aF2Fv4rrcq48eRo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'kebab-express-auth-token',
  }
});
